language: elixir

matrix:
  include:
    - elixir: 1.4.5
      otp_release:
          - 19.0
          - 20.0
    - elixir: 1.5.3
      otp_release:
          - 19.0
          - 20.0
    - elixir: 1.6.6
      otp_release:
          - 19.0
          - 20.0
          - 21.0
          - 22.0
    - elixir: 1.7.4
      otp_release:
          - 19.0
          - 20.0
          - 21.0
          - 22.0
    - elixir: 1.8.2
      otp_release:
          - 20.0
          - 21.0
          - 22.0
    - elixir: 1.9.1
      otp_release:
          - 20.0
          - 21.0
          - 22.0
          - 23.0
    - elixir: 1.10.3
      otp_release:
          - 20.0
          - 21.0
          - 22.0
          - 23.0



script:
  - mix test
